# _Introduction to Python_
Run the hidden code cell below to import the data used in this course.

In [1]:
# Importing course packages; you can add more too!
import numpy as np
import math

# Import columns as numpy arrays
baseball_names = np.genfromtxt(
    fname="baseball.csv",  # This is the filename
    delimiter=",",  # The file is comma-separated
    usecols=0,  # Use the first column
    skip_header=1,  # Skip the first line
    dtype=str,  # This column contains strings
)
baseball_heights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=3, skip_header=1
)
baseball_weights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=4, skip_header=1
)
baseball_ages = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=5, skip_header=1
)

soccer_names = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=1,
    skip_header=1,
    dtype=str,
    encoding="utf", 
)
soccer_ratings = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=2,
    skip_header=1,
    encoding="utf", 
)
soccer_positions = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=3,
    skip_header=1,
    encoding="utf", 
    dtype=str,
)
soccer_heights = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=4,
    skip_header=1,
    encoding="utf", 
)
soccer_shooting = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=8,
    skip_header=1,
    encoding="utf", 
)

# General

## Quotation Marks
Variables do not need quotation marks around them.

# Lists


Lists can contain multiple data types, or lists within lists. 

In [1]:
# fam1 = ['liz', 'marc', 'jake']
# fam2 = [['liz', 3], ['marc', 5]]

## Subsetting Lists
Remember that indexes start at 0, so the first thing in the list is [0]

In [ ]:
# fam1[1]
# 'marc'

Subsetting Lists of Lists

In [ ]:
# fam2[0][0]
# 'liz'

## List Slicing
The first number in a list slice is inclusive, and the last is exclusive. So it won't include the last number

In [ ]:
# fam1[0:2]
# ['liz', 'marc']

## Changing List Elements 

In [ ]:
# fam1[1] = 13 will change the second value in the list to 13

## Add Elements to List

In [ ]:
# fam1 + ['me', 1.3]

## Remove Elements from List

In [ ]:
# del(fam1[0])

## Referencing a List
If you make a list x and set y = x, if you update y, it also updates x. You're copying the reference to list x, not just the values in x. 
If you want to make a separate list, you can do 
y = list(x) 
or 
y = x[:]

# Functions

max(fam1) will return the maximum of fam1
round() takes 2 arguments. The first is the value to round, and the second is the decimal place to round to
help() will bring up documentation and info on arguments

# Methods
Methods are essentially functions that belong to objects. Python objects are data structures like strings, integers, and lists which represent different values. Methods vary depending on the object type, so strings and integers will have different methods. You call a method on an object, so below you're calling the index method on the the fam1 list

In [ ]:
# fam1.index('liz') will return the index position of 'liz' in the list

.append() adds something to the end of the list

# Packages
You can import packages like numpy using
import numpy as np
You can import specific functions from a package like
from numpy import array

# NumPy

## NumPy Arrays
Arrays are an alternative to lists where you're able to perform calculations over the mass set of values
If you have a list called height, you can convert it to an array using
np_height = np.array(height)
You can then take np_height and do a calculation like 
new_height = np_height + 2
Or you could do a short cut of 
new_height = np.array(height) + 2

Arrays can only contain one value type (Booleans, floats).
If you add two lists containing [1, 2, 3], the output would be [1, 2, 3, 1, 2, 3]
If you add two arrays that have the same contents as above, the output would be array([2, 4, 6])

## NumPy Subsetting
bmi[1]
bmi > 23 will return an array of Boolean values where array values are greater or less than input
array([True, False, True])
Subsetting again will return the exact values above the input
array([25, 30])

## 2D NumPy Arrays
These are type numpy.ndarray, where n is n-dimensional array
2D arrays are made of a list of lists
2D arrays can subset using either way below; they do the same thing 
np_2d[0][2]
np_2d[0, 2]
A more complex way to subset would be like this. It would call a 2D array
np_2d[:, 1:2]

2D arrays enable element-wise calculations

## Attributes
Using .shape is like a method, but it doesn't have the round brackets after it

## NumPy Stats
np.mean(np_city[:, 0]) will find the mean of all the first values in all of the lists within an array
np.mean(np_city[:, 0])
np.corrcoef(np_city[:, 0], np_city[:, 1]) 

## NumPy for Generating Data
Arguments for np.random.normal()
	distribution mean
    distribution standard deviation
    number of samples

## Column Stack

Stacks 1-D arrays as columns into a 2-D array

In [2]:
np_arr1 = np.array([1,2,3,4])
np_arr2 = np.array([5,6,7,8])
print(np.column_stack((np_arr1, np_arr2)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
